<a href="https://colab.research.google.com/github/Programer1554/Data-Science-4-Sem/blob/main/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Array Manipulation

*   np.transpose(array) - To transpose array
*   np.reshape(array,shape) - To Change shape of an array
* np.resize(array,shape) - To return new array with shape
* np.flatten(array) - To flatten the array



**np.transpose()**

In [ ]:
#Create a 2D array
import numpy as np
arravali=np.array(np.random.randint(10,45,(8,2)))
print(f"The defined array is \n{arravali}")
print(f"\nThe shape of the array is {arravali.shape}")

The defined array is 
[[13 16]
 [12 39]
 [12 15]
 [25 15]
 [41 16]
 [10 28]
 [41 36]
 [15 16]]

The shape of the array is (8, 2)


In [ ]:
#Storing the transpose in another matrix object
nilgiri=np.transpose(arravali)
print(f"The transpose of the array is \n{nilgiri}")
print(f"\nThe shape of the array is {nilgiri.shape}")

The transpose of the array is 
[[13 12 12 25 41 10 41 15]
 [16 39 15 15 16 28 36 16]]

The shape of the array is (2, 8)


In [ ]:
#3D array
random_3d_array= np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3d_array}")
print(f"\nThe shape of the array is {random_3d_array.shape}")
#

The defined array is 
[[[18 21 24 22]
  [38 43 12 30]]

 [[40 26 37 40]
  [17 15 37 22]]

 [[26 28 23 15]
  [43 37 27 31]]]

The shape of the array is (3, 2, 4)


In [ ]:
#Storing the transpose of the created 3d array
transpose_3d_array=np.transpose(random_3d_array)
print(f"The transpose of the array is \n{transpose_3d_array}")
print(f"\nThe shape of the array is {transpose_3d_array.shape}")

The transpose of the array is 
[[[18 40 26]
  [38 17 43]]

 [[21 26 28]
  [43 15 37]]

 [[24 37 23]
  [12 37 27]]

 [[22 40 15]
  [30 22 31]]]

The shape of the array is (4, 2, 3)


**np.reshape(shape)**

In [ ]:
#Create a two-dimensional array
random_cohort=np.array(np.random.randint(10,45,(3,8)))
print(f"The defined array is \n{random_cohort}")
print(f"\nThe shape of the array is {random_cohort.shape}")

The defined array is 
[[25 19 31 15 23 16 11 43]
 [44 42 41 39 36 15 39 27]
 [24 40 11 35 39 43 44 37]]

The shape of the array is (3, 8)


In [ ]:
#Now we can reshpae this to 1-D, 2-D or 3-D array
new_shape=(2,6,2)
reshaped_cohort=np.reshape(random_cohort,new_shape)
print(f"The reshaped array is \n{reshaped_cohort}")
print(f"\nThe shape of the array is {reshaped_cohort.shape}")

The reshaped array is 
[[[25 19]
  [31 15]
  [23 16]
  [11 43]
  [44 42]
  [41 39]]

 [[36 15]
  [39 27]
  [24 40]
  [11 35]
  [39 43]
  [44 37]]]

The shape of the array is (2, 6, 2)


In [ ]:
new_shape=(2,-1,6)
reshaped_cohort=np.reshape(random_cohort,new_shape)
print(f"The reshaped array is \n{reshaped_cohort}")
print(f"\nThe shape of the array is {reshaped_cohort.shape}")

The reshaped array is 
[[[25 19 31 15 23 16]
  [11 43 44 42 41 39]]

 [[36 15 39 27 24 40]
  [11 35 39 43 44 37]]]

The shape of the array is (2, 2, 6)


In [ ]:
#Create a three dimensional array
random_3d_array= np.array(np.random.randint(10,45,(3,6,2)))
print(f"The defined array is \n{random_3d_array}")
print(f"\nThe shape of the array is {random_3d_array.shape}")

The defined array is 
[[[43 18]
  [21 37]
  [29 21]
  [36 18]
  [41 22]
  [30 22]]

 [[38 10]
  [11 16]
  [36 30]
  [43 17]
  [44 42]
  [33 40]]

 [[32 27]
  [22 39]
  [12 32]
  [12 41]
  [24 44]
  [39 30]]]

The shape of the array is (3, 6, 2)


In [ ]:
#Reshape the created 3D array
new_shape=(2,-1,6)
reshaped_3d_array=np.reshape(random_3d_array,new_shape)
print(f"The reshaped array is \n{reshaped_3d_array}")
print(f"\nThe shape of the array is {reshaped_3d_array.shape}")

The reshaped array is 
[[[43 18 21 37 29 21]
  [36 18 41 22 30 22]
  [38 10 11 16 36 30]]

 [[43 17 44 42 33 40]
  [32 27 22 39 12 32]
  [12 41 24 44 39 30]]]

The shape of the array is (2, 3, 6)


**np.resize(shape)**

In [ ]:
#Intialize a 3D array
random_3d_array= np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3d_array}")
print(f"\nThe shape of the array is {random_3d_array.shape}")

The defined array is 
[[[18 35 25 42 11 20]
  [23 43 31 25 23 19]
  [34 14 27 12 31 20]
  [27 35 24 32 41 22]]

 [[40 41 41 11 40 37]
  [16 12 18 17 13 17]
  [30 36 21 29 34 21]
  [18 24 42 41 17 27]]]

The shape of the array is (2, 4, 6)


In [ ]:
#Resize the created 3D array
new_shape=(2,3,6)
resized_3d_array=np.resize(random_3d_array,new_shape)
print(f"The resized array is \n{resized_3d_array}")
print(f"\nThe shape of the array is {resized_3d_array.shape}")

The resized array is 
[[[18 35 25 42 11 20]
  [23 43 31 25 23 19]
  [34 14 27 12 31 20]]

 [[27 35 24 32 41 22]
  [40 41 41 11 40 37]
  [16 12 18 17 13 17]]]

The shape of the array is (2, 3, 6)


In [ ]:
resized_3d_array.resize(new_shape)
resized_3d_array

array([[[18, 35, 25, 42, 11, 20],
        [23, 43, 31, 25, 23, 19],
        [34, 14, 27, 12, 31, 20]],

       [[27, 35, 24, 32, 41, 22],
        [40, 41, 41, 11, 40, 37],
        [16, 12, 18, 17, 13, 17]]])

**np.flatten()**

In [ ]:
#Intialize a 3D array
random_3d_array= np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3d_array}")
print(f"\nThe shape of the array is {random_3d_array.shape}")

The defined array is 
[[[43 13 39 22 15 30]
  [27 27 43 25 41 29]
  [35 32 39 27 34 10]
  [37 14 21 22 17 22]]

 [[29 10 17 43 19 28]
  [40 35 37 17 15 21]
  [41 32 40 41 27 43]
  [26 23 13 25 34 12]]]

The shape of the array is (2, 4, 6)


In [ ]:
#Flatten the 3D array
random_3d_array.flatten()

array([43, 13, 39, 22, 15, 30, 27, 27, 43, 25, 41, 29, 35, 32, 39, 27, 34,
       10, 37, 14, 21, 22, 17, 22, 29, 10, 17, 43, 19, 28, 40, 35, 37, 17,
       15, 21, 41, 32, 40, 41, 27, 43, 26, 23, 13, 25, 34, 12])

In [ ]:
#Flattens the array in row-major order with 'C'
random_3d_array.flatten(order='F')

array([43, 29, 27, 40, 35, 41, 37, 26, 13, 10, 27, 35, 32, 32, 14, 23, 39,
       17, 43, 37, 39, 40, 21, 13, 22, 43, 25, 17, 27, 41, 22, 25, 15, 19,
       41, 15, 34, 27, 17, 34, 30, 28, 29, 21, 10, 43, 22, 12])

#Next we will see how we can manipulate our numpy arrays
* np.insert- To inset items to an array
* np.append- To append items to an array
* np.delete- To delete items from an array
* np.unique- To find unique items from an array

**np.insert(arr,obj,values,axis)**
* arr: Input array
* obj: The index before which insertion is to be made
* values: The array of values to be inserted
* axis: The axis along insert in given array. If not given, arr is flattened

In [ ]:
a=np.random.randint(10,20,(2,3,4))
print(a)
print(a.shape)

[[[19 19 15 13]
  [15 17 16 17]
  [12 11 18 11]]

 [[17 13 14 19]
  [15 19 17 19]
  [15 13 10 12]]]
(2, 3, 4)


In [ ]:
#Insert along axis =0
np.insert(a,1,100,axis=0)

array([[[ 19,  19,  15,  13],
        [ 15,  17,  16,  17],
        [ 12,  11,  18,  11]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[ 17,  13,  14,  19],
        [ 15,  19,  17,  19],
        [ 15,  13,  10,  12]]])

In [ ]:
#Insert along axis=1
np.insert(a,0,50,axis=1)

array([[[50, 50, 50, 50],
        [19, 19, 15, 13],
        [15, 17, 16, 17],
        [12, 11, 18, 11]],

       [[50, 50, 50, 50],
        [17, 13, 14, 19],
        [15, 19, 17, 19],
        [15, 13, 10, 12]]])

In [ ]:
#Insert along axis=2
np.insert(a,0,200,axis=2)

array([[[200,  19,  19,  15,  13],
        [200,  15,  17,  16,  17],
        [200,  12,  11,  18,  11]],

       [[200,  17,  13,  14,  19],
        [200,  15,  19,  17,  19],
        [200,  15,  13,  10,  12]]])

**np.append(arr,values,axis)**
* arr- Array
* values- Values to be appended
* axis- Axis along which to append

In [ ]:
a= np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[5 3 5]
  [5 5 2]
  [2 3 2]]

 [[3 2 4]
  [5 2 2]
  [3 5 4]]]
(2, 3, 3)


In [ ]:
#Append a value to the array. It flattens the array and append -99 to the end
np.append(a,-99)

array([  5,   3,   5,   5,   5,   2,   2,   3,   2,   3,   2,   4,   5,
         2,   2,   3,   5,   4, -99])

In [ ]:
#Fix the axis other than axis of appending
b= np.random.randint(2,6,(2,1,3))
print(b)

[[[2 4 3]]

 [[3 4 2]]]


In [ ]:
print(a)
print(a.shape)

[[[5 3 5]
  [5 5 2]
  [2 3 2]]

 [[3 2 4]
  [5 2 2]
  [3 5 4]]]
(2, 3, 3)


In [ ]:
np.append(a,b,axis=1)

array([[[5, 3, 5],
        [5, 5, 2],
        [2, 3, 2],
        [2, 4, 3]],

       [[3, 2, 4],
        [5, 2, 2],
        [3, 5, 4],
        [3, 4, 2]]])

**np.delete(arr,obj,axis)**

*obj: Can be a slice, an integer or array of integers, indicating the subarray to be deleted from the input array

In [ ]:
a= np.random.randint(2,6,(2,3,3))
print(a)
print(a.shape)

[[[5 5 3]
  [4 3 4]
  [2 4 2]]

 [[5 2 4]
  [3 5 4]
  [4 5 2]]]
(2, 3, 3)


In [ ]:
#Delete along Axis=0
np.delete(a,(0),axis=0)

array([[[5, 2, 4],
        [3, 5, 4],
        [4, 5, 2]]])

In [ ]:
#Delete along axis=1
np.delete(a,(0,2),axis=1)

array([[[4, 3, 4]],

       [[3, 5, 4]]])

In [ ]:
a

array([[[5, 5, 3],
        [4, 3, 4],
        [2, 4, 2]],

       [[5, 2, 4],
        [3, 5, 4],
        [4, 5, 2]]])

In [ ]:
#Delete along axis=2
np.delete(a,(0,1),axis=2)

array([[[3],
        [4],
        [2]],

       [[4],
        [4],
        [2]]])

**np.unique(arr,return_index,return_counts)**

In [1]:
import numpy as np
#Initialized array
a=np.random.randint(2,20,(2,3,3))
print(a)
print(a.shape)

[[[ 4  5 11]
  [11 11 12]
  [ 2  2 18]]

 [[12 12 16]
  [ 9 11  5]
  [13  4  4]]]
(2, 3, 3)


In [2]:
np.unique(a)

array([ 2,  4,  5,  9, 11, 12, 13, 16, 18])

In [3]:
#return_counts=True
np.unique(a,return_counts=True)

(array([ 2,  4,  5,  9, 11, 12, 13, 16, 18]),
 array([2, 3, 2, 1, 4, 3, 1, 1, 1]))

In [4]:
#return_index=True
np.unique(a,return_index=True,return_counts=True)

(array([ 2,  4,  5,  9, 11, 12, 13, 16, 18]),
 array([ 6,  0,  1, 12,  2,  5, 15, 11,  8]),
 array([2, 3, 2, 1, 4, 3, 1, 1, 1]))

# Difference between copy and view
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array. The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy

Let us look at a list

In [5]:
#Lets take an example of a list
a=[1,2,3]
b=a
b[0]=10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [6]:
#Let's use the copy method
a=[1,2,3]
b=a.copy()
b[0]=10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


In [7]:
#Now let us look at an array
a=np.array([2,34,12])
b=a
b[0]= -999
print(b)
print(a)

[-999   34   12]
[-999   34   12]


In [8]:
a=np.array([2,34,12])
b=a.copy()
b[0]= -999
print(b)
print(a)

[-999   34   12]
[ 2 34 12]


#Basic Operations & Functions


*   np.add()- Adding two arrays
*   np.subtract()- Subtracting two arrays
*   np.multiply()- Multiplying two arrays
*   np.divide()- Dividing two arrays
*   np.sum()- Sum of items in an array
*   np.min()- Minimum of items in an array
*   np.max()- Maximum of items in an array
*   np.mean()- Mean of items in an array
*   np.sort()-Sorting an array





In [10]:
np.arange(3)+ 5

array([5, 6, 7])

In [11]:
np.ones((3,3))+ np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [12]:
np.arange(3).reshape((3,1))+ np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [13]:
np.arange(3).reshape((3,1))+ np.arange(4)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [14]:
np.arange(2)

array([0, 1])

In [20]:
#Example 2
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(1,10,(2,4))
print(b)

[[4 4 3 2]
 [2 4 5 2]]
[[3 4 1 2]
 [9 9 1 9]]


In [23]:
np.add(a,b)

array([[ 7,  8,  4,  4],
       [11, 13,  6, 11]])

In [25]:
#Let's multiply two arrays
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(0,5,(2,4))
print(b)

[[4 3 4 3]
 [4 3 2 5]]
[[4 2 2 3]
 [3 1 4 4]]


In [26]:
np.multiply(a,b)

array([[16,  6,  8,  9],
       [12,  3,  8, 20]])

In [27]:
#Let's divide two arrays
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(1,6,(2,4))
print(b)

[[3 4 2 2]
 [5 2 2 5]]
[[3 5 2 2]
 [4 2 2 4]]


In [28]:
np.divide(a,b)

array([[1.  , 0.8 , 1.  , 1.  ],
       [1.25, 1.  , 1.  , 1.25]])

In [29]:
#Aggregation problems
a=np.random.randint(5,9,(2,4))
print(a)

[[5 8 7 7]
 [7 7 5 5]]


In [30]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

51
[12 15 12 12]
[27 24]


In [32]:
#Calculate minimum
print(np.min(a))
print(np.min(a,axis=1)) #Across Column

#Sort the array
a=np.random.randint(0,20,(3,3))
print(a)

5
[5 5]
[[ 7  6 17]
 [ 0  7 12]
 [15  6 13]]


In [33]:
print(np.sort(a,axis=0))#Ascending

[[ 0  6 12]
 [ 7  6 13]
 [15  7 17]]


In [35]:
print(np.sort(a,axis=1))

[[ 6  7 17]
 [ 0  7 12]
 [ 6 13 15]]


In [36]:
print(-np.sort(-a,axis=1)) #Descending

[[17  7  6]
 [12  7  0]
 [15 13  6]]


In [38]:
sum(np.arange(3)*np.arange(3).transpose())

5